[project]
name = "mrva"
version = "0.5.0"
description = "A CLI tool for running local CodeQL multi-repo variant analysis"
license = "AGPL-3.0"
readme = "README.md"
requires-python = ">=3.9,<4"
authors = []
dependencies = [
    "httpx",
    "jinja2 (>=3.1.6,<4.0.0)",
]
classifiers = [
    "Environment :: Console",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Security",
]

[project.urls]
homepage = "https://github.com/trailofbits/mrva"
repository = "https://github.com/trailofbits/mrva"

[project.scripts]
mrva = "mrva.main:main"

[tool.poetry]
packages = [{include = "mrva"}]

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
pytest-cov = "^4.0"
pytest-asyncio = "^1.1.0"
pre-commit = "^4.2.0"

[tool.poetry.group.dev]
optional = true

[tool.coverage.run]
source = ["mrva"]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
